version: '2'

services:
  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: smartgrow
      MYSQL_ROOT_PASSWORD: smartgrow
    expose:
      - 3306

  smart-grow:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "443:443"
      - "80:80"
    environment:
      APP_ENV: prod
    depends_on:
      - mysql-db